import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Nav } from "@/components/nav";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AnimatedGrid } from "@/components/ui/animated-grid-background";
import { Toaster } from "@/components/ui/sonner";
import { getCurrentUserQuery } from "@/queries";
import { AuthProvider } from "@/components/auth/auth-context";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#432dd7",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUserQuery();

  return (
    <html
      lang="pl"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-screen flex flex-col bg-background w-screen overflow-x-hidden">
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AnimatedGrid />
          <TooltipProvider>
            <AuthProvider initialUser={user}>
              <header className="lg:py-[1.15rem] lg:px-0 max-w-5xl mx-auto w-full flex justify-center sticky top-0 z-10">
                <Nav />
              </header>
              {children}
              <Footer />
            </AuthProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
