import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Nav } from "@/components/nav";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AnimatedGrid } from "@/components/ui/animated-grid-background";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: '#432dd7'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background w-screen overflow-x-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AnimatedGrid />
          <TooltipProvider>
            <header className="lg:py-[1.15rem] lg:px-0 max-w-6xl mx-auto w-full flex justify-center sticky top-0 z-10">
              <Nav />
            </header>
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
